//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsServisSlanjeMaila
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radi
    {
        public string DjelatnikID { get; set; }
        public int SmjenaID { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Smjena Smjena { get; set; }
    }
}
