//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_a_Car
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iznajmljivanje
    {
        public int IznamljivanjeID { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public double JedinicnaCijena { get; set; }
        public System.DateTime DatumPocetka { get; set; }
        public System.DateTime DatumKraja { get; set; }
        public int BrojDana { get; set; }
        public string DjelatnikID { get; set; }
        public Nullable<int> RacunID { get; set; }
        public string VoziloID { get; set; }
        public string KlijentID { get; set; }
        public double UkupnaCijena { get; set; }
        public bool Naplaceno { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Korisnik Korisnik1 { get; set; }
        public virtual Racun Racun { get; set; }
        public virtual Vozilo Vozilo { get; set; }
    }
}
