//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_a_Car
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnik()
        {
            this.PovratnaInformacija = new HashSet<PovratnaInformacija>();
            this.Radi = new HashSet<Radi>();
            this.Rezervacija = new HashSet<Rezervacija>();
            this.Iznajmljivanje = new HashSet<Iznajmljivanje>();
            this.Iznajmljivanje1 = new HashSet<Iznajmljivanje>();
        }
    
        public string KorisnikID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Lozinka { get; set; }
        public string KorisnickoIme { get; set; }
        public System.DateTime DatumRodenja { get; set; }
        public string Adresa { get; set; }
        public string Mobitel { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string IBAN { get; set; }
        public int TipKorisnika { get; set; }
    
        public virtual TipKorisnika TipKorisnika1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PovratnaInformacija> PovratnaInformacija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Radi> Radi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Iznajmljivanje> Iznajmljivanje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Iznajmljivanje> Iznajmljivanje1 { get; set; }
    }
}
