//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_a_Car
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        public int RezervacijaID { get; set; }
        public string Opis { get; set; }
        public System.DateTime DatumRezervacije { get; set; }
        public System.DateTime DatumPocetka { get; set; }
        public System.DateTime DatumKraja { get; set; }
        public string VoziloID { get; set; }
        public string KorisnikID { get; set; }
        public double JedinicnaCijena { get; set; }
        public int BrojDana { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Vozilo Vozilo { get; set; }
    }
}
