//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_a_Car
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozilo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vozilo()
        {
            this.PovratnaInformacija = new HashSet<PovratnaInformacija>();
            this.Rezervacija = new HashSet<Rezervacija>();
            this.Iznajmljivanje = new HashSet<Iznajmljivanje>();
        }
    
        public string VoziloID { get; set; }
        public string Naziv { get; set; }
        public int GodinaProizvodnje { get; set; }
        public int SnagaMotora { get; set; }
        public int BrojSjedala { get; set; }
        public int Kilometri { get; set; }
        public System.DateTime DatumRegistracije { get; set; }
        public int KategorijaID { get; set; }
        public int TipMotoraID { get; set; }
        public double CijenaPoDanu { get; set; }
    
        public virtual Kategorija Kategorija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PovratnaInformacija> PovratnaInformacija { get; set; }
        public virtual TipMotora TipMotora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Iznajmljivanje> Iznajmljivanje { get; set; }
    }
}
